### ISSUE TITLE
Include required module or document requirement

### ISSUE THREAD

**Issue by wsmelton** [PrateekKumarSingh/AzViz#1]
Use of the `Export-PSGraph` command means the `PSGraph` module has to be installed for the functionality to exists on a given user's machine. I was not able to find any direct reference to this in the README file.

Options would be to either include this in your manifest, document it in your README, or have the function check if the module exists before trying to call the export command.

**Comment by PrateekKumarSingh** [comment]
'PSGraph' added as dependency in the module manifest, should be good in latest versions.
