### ISSUE TITLE
'Graph' is not recognized as the name of a cmdlet, function

### ISSUE THREAD

**Issue by dkumarscj** [PrateekKumarSingh/AzViz#2]
Graph : The term 'Graph' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At C:\Users\xxx\xxxx\Cloud Foundation\AzViz-master\src\public\Get-AzNetworkVizualization.ps1:105 char:5
+     Graph 'AzureTopology' @{overlap = 'false'; splines = 'true' ; ran ...
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (Graph:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
VERBOSE: Graph Exported to path:

**Comment by milind8451** [comment]
Same error for me.

**Comment by PrateekKumarSingh** [comment]
Added 'PSGraph' as dependency for this module and in latest version we don't get this error anymore.
