### ISSUE TITLE
Best Practices - RequiredModules

### ISSUE THREAD

**Issue by TheTaylorLee** [PrateekKumarSingh/AzViz#25]
Your "Script Module" file "AzViz.psm1"  is installing PSGraph and AZ modules if not found when your module loads. This goes against best practices and shouldn't be handled there. This creates a situation where someone might have this module load from another source and it starts installing modules that they didn't intend to install, and they can't find what module is installing those other modules. 

Best Practice would be to use your Module Manifest to specify required modules. In that scenario the offending module that is installing other modules becomes more discoverable.

#Remove This   ##Please
`# verify dependent modules are loaded
$DependentModules = 'PSGraph', 'az'
$Installed = Import-Module $DependentModules -PassThru -ErrorAction SilentlyContinue | Where-Object { $_.name -In $DependentModules }
$Missing = $DependentModules | Where-Object { $_ -notin $Installed.name }
if ($Missing) {
    Write-Verbose "    [+] Module dependencies not found [$Missing]. Attempting to install."
    Install-Module $Missing -Force -AllowClobber -Confirm:$false -Scope CurrentUser
    Import-Module $Missing
}`

-/u/SpacezCowboy

**Comment by TheTaylorLee** [comment]
My reasons for this are slightly selfish. I'm looking to include this module in a portable PowerShell deployment that I make use of. I don't always want to have dependent modules load. So truthfully I would like to have no required modules install when deploying this. I can modify your manifest, but noticed how this was done and thought the issue above strongly applies.

**Comment by PrateekKumarSingh** [comment]
@TheTaylorLee this has been fixed in recent commit to this repository. Closing the issue now.
