### ISSUE TITLE
Resource Dependency requirements

### ISSUE THREAD

**Issue by devlife** [PrateekKumarSingh/AzViz#34]
I did `Export-AzViz` and used all of the default values but the only resource dependency arrow drawn was from a web app to the resource group. Under what circumstances would a dependency be drawn between a web app and application insights, for example?

**Comment by PrateekKumarSingh** [comment]
Hey @devlife, right now resource dependency is drawn on basis of:

1. `DependsOn` property in the Resource Group ARM template which is exported/parsed automatically to obtain this property
2. If a Network Watcher is detected in the Location of the target Resource Group, then it can run `Get-AzNetworkWatcherTopology` cmdlet to obtain network associations/dependency like `VM -> NIC`

I'll add more documentation to make this point clear.
