### ISSUE TITLE
Direction Parameter Bug

### ISSUE THREAD

**Issue by TheTaylorLee** [PrateekKumarSingh/AzViz#35]
Specifying left-to-right no longer functions. It will default to top-to-bottom regardless of entry.

**Comment by PrateekKumarSingh** [comment]
I'll pick this one up in next release. Thanks for creating an issue 👍

**Comment by TheTaylorLee** [comment]
Awesome, Thanks for your work.

**Comment by bkarstaedt** [comment]
This is still the case :(. Any updates on this?
