### ISSUE TITLE
Feedback - Output.png filename.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PrateekKumarSingh/AzViz#54]
Just a feedback!

I'm sure you could generate the output file name with resource group name, or provide  a parameter to name the output file.

**Comment by PrateekKumarSingh** [comment]
@MaximoTrinidad, you can use `Export-AzViz -OutputFilePath` parameter to provide exact name and file path for the output image generated.

Also, I got the feedback to add a wrapper function to call `Export-AzViz` for all resource groups in the subscription. And I'm considering to provide a feature to automatically name the output files with 'resource group name'
