### ISSUE TITLE
Import module fails with no exported commands

### ISSUE THREAD

**Issue by J0R3D1N** [PrateekKumarSingh/AzViz#6]
I cloned your repo, installed PSGraph (since its dependant), but no commands were exported to the PS Session.

![image](https://user-images.githubusercontent.com/46932720/67045463-32adbc80-f0e3-11e9-8a24-61b2fb23da6d.png)

**Comment by junecastillote** [comment]
Try to edit line 12 in the AzViz.psd1. Uncomment the RootModule and add AzViz.psm1 like in the screenshot below. Then re-import the module.
![image](https://user-images.githubusercontent.com/15041242/67049370-a940cd80-f168-11e9-83c4-ec71b3395383.png)

**Comment by PrateekKumarSingh** [comment]
This issue is fixed in the most recent version of the module, please download from PSGallery.
